### ISSUE TITLE
MongoServerSelectionError: Server starup failed

### ISSUE THREAD

**Issue by vipulwairagade** [zishone/oas-express-starter#43]
This is what I got printed into my console when I start the application.

```
{"service":"oas-express-starter","version":"0.1.0-development","env":"development","hostname":"1032","error.name":"MongoServerSelectionError","error.reason.type":"Unknown","error.reason.setName":null,"error.reason.maxSetVersion":null,"error.reason.maxElectionId":null,"error.reason.stale":false,"error.reason.compatible":true,"error.reason.compatibilityError":null,"error.reason.logicalSessionTimeoutMinutes":null,"error.reason.heartbeatFrequencyMS":10000,"error.reason.localThresholdMS":15,"error.reason.commonWireVersion":null,"timestamp":"2021-03-12T08:21:05.552Z","level":"error","message":"Server startup failed"}
```
I googled about it and found the similar error listed in mongodb issues. Issue listed [here](https://jira.mongodb.org/browse/NODE-3052?jql=summary%20~%20%22MongoServerSelectionError*%22%20OR%20description%20~%20%22MongoServerSelectionError*%22%20ORDER%20BY%20lastViewed%20DESC)

It's something that I have to use `directConnection:true`.
I am on mongo version 4.4.4 and package version 3.6.3

**Comment by zishone** [comment]
Hi @vipulwairagade 

I have some questions so I can get more context :)
- Does your MongoDB server that have a replication set?
- Have you already created a `.env` file and set your MongoDB server's `uri` to `CONFIG_DB_URI`?

**Comment by vipulwairagade** [comment]
Hi @zishone ,
Thanks for the details. I figured out what was the issue. It was pretty simple and I somehow missed it. In your `.env.defaults` db uri was `mongodb://mongodb:27017` which I copy pasted in `.env` assuming the port number same but on windows for my mongo server I had to use `mongodb://127.0.0.1:27017`, then I was able to start server.

**Comment by zishone** [comment]
Awesome! glad I was able to help :)
